version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["pygyat", "main.gyat"]  
    # command: ["python=3", "main.py"]